esphome:
  name: garage-door-opener
  friendly_name: garage-door-opener

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret garage_encryption_key

ota:
  - platform: esphome
    password: !secret garage_esphome_password

ethernet:
  type: W5500
  mosi_pin: GPIO11
  miso_pin: GPIO12
  clk_pin: GPIO13
  cs_pin: GPIO14
  reset_pin: GPIO9
  interrupt_pin: GPIO10
  clock_speed: 25MHz

packages:
  garage01: !include
    file: garage-door-package.yaml
    vars:
      door_id: garage01
      door_name: "Garage 01"
      relay_pin: GPIO21
      open_sensor_pin: GPIO17
      closed_sensor_pin: GPIO18

  garage02: !include
    file: garage-door-package.yaml
    vars:
      door_id: garage02
      door_name: "Garage 02"
      relay_pin: GPIO48
      open_sensor_pin: GPIO47
      closed_sensor_pin: GPIO42
